src/components/tabs/tabs.tsx

This adds a mutation Observer to tabs component so that if there is a change in fw-tab, the entire
component re-renders

fix(tabs): react to changes within fw-tabs

---

src/components.d.ts
src/components/tab/readme.md
src/components/tab/tab.tsx
src/components/tabs/readme.md
src/components/tabs/tabs.e2e.ts
src/components/tabs/tabs.scss
src/components/tabs/tabs.stories.mdx
src/components/tabs/tabs.tsx

This PR adds `disabled` as property for `fw-tab`. Also now, you can render HTML as a tab header.
Tested on Storybook. All test cases pass.

Tab Fixes and Added Features

---

src/components/datepicker/datepicker.scss
src/components/datepicker/datepicker.tsx

fixes the closing of a datepicker when multiple datepickers are opened.
fix #98
This has been tested locally

fix(datepicker): fixes closing the datepicker as designed

---

src/components/select/select.scss

The select dropdown must be absolutely positioned with respect to the select-container. It falls
back to the window. This becomes an issue when the window itself doesn't scroll but the container is
scrolled out of view. The dropdown ends up being incorrectly positioned.
Refer the image below to see how the dropdown position is unaffected by its container's position. 
1. Create a modal and add a fw-select component out of view (below max height).
2. Scroll the fw-select up into the view and open the menu.
3. The menu must appear right beneath the select input.
See image below to see the fix. Notice how the menu travels with the container.

style(select.scss): position select dropdown wrt container instead of window. Incorrect position

---

src/components/button/button.scss

On setting a margin on the component from outside, it was not getting applied. This fix adds
`display:inline-block` to make the component respect the margin.
fix #134
Tested locally on storybook

fix(fw-button): fixes CSS issues with external CSS

---

src/components.d.ts
src/components/dropdown-button/dropdown-button.scss
src/components/dropdown-button/dropdown-button.tsx
src/components/dropdown-button/readme.md

Add disabled prop to dropdown button
fix #145

feat(dropdown-button): add disabled prop

---

src/components/input/input.scss

Added CSS styles to hide arrows in webkit and mozilla browsers
fix #150

fix(input): hides arrows in input type number

---

src/components/label/label.scss
src/components/label/readme.md
src/index.html

introduce css variables for label padding
fix #181

feat(fw-label): introduce css variables for label padding

---

package-lock.json
packages/crayons-core/src/components/datepicker/readme.md
packages/crayons-core/src/components/input/readme.md
packages/crayons-core/src/components/options-list/readme.md
packages/crayons-core/src/components/popover/readme.md
packages/crayons-core/src/components/select-option/readme.md
packages/crayons-core/src/components/select/readme.md
packages/crayons-core/src/components/timepicker/readme.md

chore: updated readme to include fw-popover, fw-list-options, fw-select-option and their dependencies

---

packages/crayons-core/src/components/radio-group/radio-group.tsx

Call to componentOnReady is removed
This is tested by rendering the component in the CRA for react o/p target and verified it for web component by rendering it in index.html

fix(radio-group): remove call to componentOnReady in connected callback

---

packages/crayons-core/src/components/popover/popover.scss
packages/crayons-core/src/components/popover/readme.md

-  `--popover-min-height` and `--popover-max-height` were defined at the `:host` selector, so passing them as props was not possible if we need to change heights.
- Add `overscroll-behavior-y`to prevent scroll chaining. In scenarios where we have one select inside another select, upon reaching the end of inner scroll, outer scroll starts to happen, preventing this behaviour by adding this prop.

fix(popover): prevent scroll chaining and expose props for min, max heights

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/button/button.tsx
packages/crayons-core/src/components/modal-content/modal-content.scss
packages/crayons-core/src/components/modal-content/readme.md
packages/crayons-core/src/components/modal-title/modal-title.scss
packages/crayons-core/src/components/modal-title/modal-title.tsx
packages/crayons-core/src/components/modal-title/readme.md
packages/crayons-core/src/components/modal/modal.e2e.ts
packages/crayons-core/src/components/modal/modal.scss
packages/crayons-core/src/components/modal/modal.stories.mdx
packages/crayons-core/src/components/modal/modal.tsx
packages/crayons-core/src/components/modal/readme.md

Added Slider as a new variation to the existing Modal component. 
Code:
```
<fw-button modal-trigger-id='modal-slider'> Open slider </fw-button>
<fw-modal id='modal-slider' slider='true'>
<fw-modal-title>
<span style="font-weight: bold;">Header text</span>
</fw-modal-title>
<fw-modal-content>
<div>Content text</div>
</fw-modal-content>
<fw-modal-footer>
<fw-button>OK</fw-button>
</fw-modal-footer>
</fw-modal>
```
How to run vuepress sample:
1. From root of project run `npm run build` && `npm run docs:dev`
2. Open the link that shows up in console after running both commands.
3. Navigate to Modals in sidebar.
4. Scroll down to sliders section.
Screenshot:
Tested the implementation when documenting. The variation seems to work fine in both vuepress and storybook.
Tested by importing react …

feat(slider): Adding new slider variation to modal component

---

packages/crayons-core/src/components/button/button.scss

- Use correct units for `margin-left` property without which the property would not be valid and will not be applied as expected.

fix(button-group): use correct units for margin-left

---

packages/crayons-core/src/components/toast-message/toast-message.e2e.ts
packages/crayons-core/src/components/toast-message/toast-message.scss
packages/crayons-core/src/components/toast-message/toast-message.tsx

remove styling from host to avoid styles getting overridden by global styles. Created a container and add styles instead of having the styles on the host element

fix(toast): remove styling from host to avoid styles getting overridden by global styles

---

packages/crayons-core/src/components/radio/radio.e2e.ts
packages/crayons-core/src/components/radio/radio.scss
packages/crayons-core/src/components/radio/radio.tsx

Remove styling from host to avoid styles getting overridden by global styles. Created a container and add styles to it instead of having the styles on the host element

fix(radio): remove class from host and apply on container to avoid getting overridden by global styles

---

packages/crayons-core/src/components/checkbox/checkbox.e2e.ts
packages/crayons-core/src/components/checkbox/checkbox.scss
packages/crayons-core/src/components/checkbox/checkbox.tsx

Remove styling from host to avoid styles getting overridden by global styles. Created a container and add styles to it instead of having the styles on the host element

fix(checkbox): remove class from host and apply on container to avoid getting overridden by global styles

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/avatar/readme.md
packages/crayons-core/src/components/datepicker/readme.md
packages/crayons-core/src/components/options-list/list-options.tsx
packages/crayons-core/src/components/options-list/readme.md
packages/crayons-core/src/components/popover/popover.tsx
packages/crayons-core/src/components/select-option/readme.md
packages/crayons-core/src/components/select-option/select-option.tsx
packages/crayons-core/src/components/select/readme.md
packages/crayons-core/src/components/select/select.tsx
packages/crayons-core/src/components/tag/tag.tsx
packages/crayons-core/src/components/timepicker/readme.md
packages/crayons-core/src/utils/types.ts

feat(fw-select): added prop to display avatar

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/tab/tab.e2e.ts
packages/crayons-core/src/components/tab/tab.scss
packages/crayons-core/src/components/tab/tab.tsx
packages/crayons-core/src/components/tabs/readme.md
packages/crayons-core/src/components/tabs/tabs.scss
packages/crayons-core/src/components/tabs/tabs.stories.mdx
packages/crayons-core/src/components/tabs/tabs.tsx

Remove styling from host to avoid styles getting overridden by global styles. Created a container and add styles to it instead of having the styles on the host element

fix(tab): remove class from host to avoid getting overridden by global styles

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/checkbox/checkbox.e2e.ts
packages/crayons-core/src/components/checkbox/checkbox.stories.mdx
packages/crayons-core/src/components/checkbox/checkbox.tsx
packages/crayons-core/src/components/checkbox/readme.md

- `label` prop is marked as deprecated.
-  When both `label` and `description` are present, `description` takes priority.

refactor(checkbox): revert checkbox to previous behaviour and mark label prop as deprecated

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/radio-group/readme.md
packages/crayons-core/src/components/radio/radio.e2e.ts
packages/crayons-core/src/components/radio/radio.scss
packages/crayons-core/src/components/radio/radio.stories.mdx
packages/crayons-core/src/components/radio/radio.tsx
packages/crayons-core/src/components/radio/readme.md

- `label` prop is marked as deprecated.
-  When both `label` and `description` are present, `description` takes priority.

refactor(radio): revert checkbox to previous behaviour and mark label prop as deprecated

---

styles/_utils.scss
styles/mixins/_typography.scss
www/css-utils/card/readme.md
www/css-utils/spacing/readme.md
www/css-utils/typography/readme.md

In this PR,
- Changed the class names of typography related css utils.
- Added a font weight util to typography section.
- Used rem units instead of px units for typography and spacing css utils.
- Improved documentation.
Testing using Vuepress docs.

fix(css-utils): improving class names in typography css utils

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/data-table/custom-cells/user/custom-cell-user.tsx
packages/crayons-core/src/components/data-table/custom-cells/user/readme.md
packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.stories.mdx
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/utils/types.ts

1. Select all rows 
2. Making orderIndex of columns optional property. Renaming orderIndex to position.
3. a11y improvements to support custom cell variants. 
*Kindly review the PR as individual commits as this PR consists of changes across 7 files.*
- Emits a 'fwSelectAllChange' event along with the current list of selected rowIds.
https://user-images.githubusercontent.com/61269786/147311804-2769234b-8212-4ab3-812b-5a972387ff4d.mov
- Optional property.
- Renamed to position. Done to make it similar to legos API.
- If only few columns have position property, they will be sorted and shown first.
https://user-images.githubusercontent.com/61269786/147312681-9655f7dc-8311-4c78-b0c2-fe59bee7da8d.mov
- If inner component is focusable, then the component is automatically focus when focus lands …

feat(data-table): adding select all rows to DataTable component

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/accordion/readme.md
packages/crayons-core/src/components/pill/pill.e2e.ts
packages/crayons-core/src/components/pill/pill.scss
packages/crayons-core/src/components/pill/pill.stories.mdx
packages/crayons-core/src/components/pill/pill.tsx
packages/crayons-core/src/components/pill/readme.md

fw-pill displays an informational text component with icon.
<br>
Icon inside the pill must be set with attribute `slot="icon"` and it could either be `fw-icon` or customised with images or SVG icons as required.
```html live
<fw-pill color="blue">
<fw-icon name="info" slot="icon"></fw-icon>
Response Received
</fw-pill>
```

feat(pill): Adding pill component

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/pill/pill.scss
packages/crayons-core/src/components/pill/pill.stories.mdx
packages/crayons-core/src/components/pill/pill.tsx
packages/crayons-core/src/components/pill/readme.md

Set custom pill color without setting attribute color as custom for better user experience to use the component.

refactor: Set custom pill color without setting attribute color as custom

---

packages/crayons-core/src/components/modal/modal.scss

**Issue:** 
Slider variant in Modal component appears in left side rather than the expected right side.
**Fix:** 
Flex justify-content 'right' does not work consistently across browsers. So changing the property value to 'flex-end'.
Tested the fix in Safari, chrome browsers.

fix(modal): slider variant position justify-content to flex-end

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/button/readme.md
packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/components/skeleton/readme.md
packages/crayons-core/src/index.html
packages/crayons-core/src/utils/types.ts

This PR includes a feature that gives the ability to individually perform actions on a row. Row actions configuration can be passed to the data-table as prop just like we do rows and columns. Made all necessary accessibility related changes to support row actions.
https://user-images.githubusercontent.com/61269786/148520524-365bcb44-a628-48d8-83c0-5a7c0872457a.mov
```js
const rowActions = [{
"name": "Alert",
"handler": (rowData) => {
window.alert(rowData.name);
}
}, {
"name": "Delete",
"handler": async (rowData) => {
let deletePromise = new Promise((resolve, reject) => {
const dataTable = document.querySelector('#datatable-4');
setTimeout(() => {
if (dataTable) {
dataTable.rows = dataTable.rows.filter((row) => (row.id !== rowData.id));
resolve();
} else {
reject();
}
}, 3000); 
});
await …
```

feat(data-table): adding row actions feature to fw-data-table

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md

Changing isTableLoading to isLoading state.

refactor(data-table): changing isTableLoading state to isLoading

---

packages/crayons-core/src/components/tag/tag.scss
packages/crayons-core/src/components/tag/tag.tsx

increased font size to 14px and changed padding/margin

fix(fw-tag): font size and padding fix

---

packages/crayons-core/src/components/checkbox/checkbox.e2e.ts
packages/crayons-core/src/components/checkbox/checkbox.tsx
packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/dropdown-button/dropdown-button.e2e.ts

- Emit `fwChange` from checkbox only on useraction.
- Fix tests to accommodate the same.

fix(checkbox): Fix checkbox event emission

---

packages/crayons-core/src/components/tabs/tabs.tsx

- fix tabs activation on attribute change on `fw-tabs`.

fix(tabs): fix tabs activation on attribute change

---

packages/crayons-core/src/components/skeleton/readme.md
packages/crayons-core/src/components/skeleton/skeleton.scss
packages/crayons-core/src/components/skeleton/skeleton.tsx

When skeleton count is 1, we won't need a margin bottom in most cases. If there is a margin, we are having to reset it unnecessarily when using in other components like table. This PR remove margin bottom if the skeleton count is 1.

fix(skeleton): removing margin-bottom when skeleton count is 1

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/button/button.scss
packages/crayons-core/src/components/button/button.tsx
packages/crayons-core/src/components/button/readme.md
packages/crayons-core/src/components/data-table/custom-cells/icon/custom-cell-icon.tsx
packages/crayons-core/src/components/data-table/custom-cells/icon/readme.md
packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/components/icon/readme.md
packages/crayons-core/src/utils/types.ts

Reference to old PR, has review comments: https://github.com/freshworks/crayons/pull/379. Closing old PR as base branch was squash merged to canary.
- Adding 'icon' variant for Table cell.
- Ability to have row actions as icon buttons.
- Exposing a method to select/unselect all rows in the table.
- Adding 'textAlign' column configuration to align text in a particular column. Ex: Icons columns have center aligned text.
```js 
const columns = [{
"key": "icon",
"text": "Object Icons",
"variant": "icon"
}]
```
Example:
```js
const columns = [{
"key": "name",
"text": "Name",
"textAlign": "center"
}]
```
Example: (Icons column is center aligned)
```js
const rowActions = [{
name: 'Edit',
iconName: 'edit',
handler: (rowData) => {
console.log(rowData);
}
}];
```
Example:
```js
const dataTable = …
```

feat(data-table): adding 'icon' cell variant, column text-align, icon button in row actions, selectAllRows api to data table

---

packages/crayons-core/src/components/data-table/data-table.tsx

Fix for rowActions async function handler showing shimmer when being called.
Tested in Stencil test app, react framework. Both tested on Chrome browser.

fix(data-table): rowActions async function handler showing shimmer

---

packages/crayons-core/crayons-react/index.ts
packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/format-date/format-date-util.ts
packages/crayons-core/src/components/format-date/format-date.e2e.ts
packages/crayons-core/src/components/format-date/format-date.stories.mdx
packages/crayons-core/src/components/format-date/format-date.tsx
packages/crayons-core/src/components/format-date/readme.md
packages/crayons-core/src/global/crayons.ts
packages/crayons-core/src/index.ts

- Adding `format-date` web component to enable date formatting based on locale.
- Exposing a controller `DateFormatController` to call format date as a method.

feat(format-date): format date using Intl.DateTimeFormat API

---

packages/crayons-core/src/components/input/input.e2e.ts
packages/crayons-core/src/components/input/input.tsx

Make `fw-input` work similar to native `input` element for `decimal` and `number` usecases

fix(fw-input): handle number,decimal input usecase

---

packages/crayons-core/src/components/data-table/data-table.scss

When hovering over a row in table, cursor should not be pointer. 
Tested with examples in Vuepress documentation site.

fix(data-table): row hover cursor fix

---

packages/crayons-core/src/components/pagination/pagination.tsx

The end value was not updated properly for the change in the total prop. This happens during the search scenario where the total is dynamically updated.

fix(fw-pagination): end value not updated on total prop change

---

packages/crayons-core/src/components/select/select.scss
packages/crayons-core/src/components/select/select.tsx

Fix the tag padding issue in case of multi-select.

fix(fw-select): fixed the padding issue on multi-select

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/input/input.scss
packages/crayons-core/src/components/input/input.tsx
packages/crayons-core/src/components/input/readme.md
styles/_theme.scss

- changed the disabled background-color to #f7f9fa 
- removed the bottom spacing on the input and increase the font-size to 14px
- reduced the size of the close icon to 8px
- changed the font-weight for the disabled state and placeholder
- exposed css variables to change the normal state font color of label and hint
- modified fw-input as a block element so that consuming component can add their margin or padding
- Added slots to create custom input as shown below

feat(fw-input): Added slots and modified styles for fw-input based on DSM

---

packages/crayons-core/src/components/checkbox/checkbox.scss

- Showing pointer cursor on entire width of `fw-checkbox`

feat(checkbox): adding pointer cursor for checkbox container

---

packages/crayons-core/src/components/modal-title/modal-title.scss

Fix modal description line height issue.
Tested with sample in Vuepress docs.

fix(modal): reduce line height of description in modal to support multiline.

---

packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx

- Making isLoading property for table as a mutable property.
- Removing table last row border as datatable generally does not have a border on its own.

fix(data-table): isloading as mutable property

---

packages/crayons-core/src/components/button/button.tsx
packages/crayons-core/src/components/modal/modal.scss
packages/crayons-core/src/components/popover/popover.scss
packages/crayons-core/src/components/popover/popover.tsx
packages/crayons-core/src/components/popover/readme.md
packages/crayons-core/src/components/tooltip/tooltip.scss

- Tooltip radius, font-weight fixes.
- Modal slider button from 40px to 24px as per DSM.
- Popover error on window change.
Tested in Chrome, Firefox, Safari browsers.

fix(tooltip): updating tooltip radius, modal close button styling

---

packages/crayons-core/src/components/drag-container/drag-container.scss
packages/crayons-core/src/components/drag-container/drag-container.tsx
packages/crayons-core/src/components/drag-container/readme.md
packages/crayons-core/src/components/drag-item/drag-item.scss
packages/crayons-core/src/components/drag-item/drag-item.tsx
packages/crayons-core/src/utils/draggable.ts

- Fixed the drag and drop not working properly in safari browser
- Converted fw-drag-container and fw-drag-item to a block element
- Added placeholder when the copy prop is set false
- Fixed the CSS issue in fw-drag-item
- Added lock icon to pinned fw-drag-item
In dragLeave event the fromElement and relatedTarget value is null in safari, this triggers the
dragContainer's leave logic thus removing the placeholder/drag element. To fix this  the logic to
remove the placeholder / drag element is moved from dragLeave event to dragEnd event.

fix(fw-drag-container): fixed the drag issue in safari 

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/utils/index.ts

- Showing shimmer on initial table load.
https://user-images.githubusercontent.com/61269786/153803016-40484f4c-e7b0-41aa-8e57-25cc1002f09e.mov
- From root of project run npm run docs:dev
- Open the link that shows up in console after running above command.
- Navigate to DataTable component in sidebar
Tested in Chrome, FIrefox, Safari browsers.

feat(data-table): showing shimmer on initial table load

---

packages/crayons-core/src/components/options-list/list-options.tsx
packages/crayons-core/src/components/select/select.tsx

Comparsion with the `next` branch event conventions
| Component |  Before | After |
| ------------ | ------------- | ------------- | 
| fw-list-options | fwChange.emit({ value, selectedOptions })  | fwChange.emit({ value, meta: { selectedOptions } })  |
** BREAKING CHANGES **
`fw-list-options` : selectedOptions field will now be part of meta field in the event detail for fwChange. Now it can be accessed using event.detail.meta.selectedOptions instead of event.detail.selectedOptions

feat(list-options): applying event standardisation for list-options as well

---

packages/crayons-core/src/utils/draggable.ts

Fixed the issue where adding a drag element to another container throws error during Drop Event.

fix(fw-drag-container): fixed the insertElement issue on Drop

---

packages/crayons-core/src/components/datepicker/datepicker.tsx
packages/crayons-core/src/components/popover/popover.scss

fix(popover): make overlay height to 100% of parent height not 100vh and use allowDeselect in datepicker

---

packages/crayons-core/src/components/data-table/custom-cells/anchor/readme.md
packages/crayons-core/src/components/data-table/custom-cells/icon/readme.md
packages/crayons-core/src/components/data-table/custom-cells/user/readme.md
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md

Issue: 
Cell variant components appear empty in data-table cell in CO UI staging environment.
Fix: 
This was happening due to stencil not picking up cell variants as dependency for data-table as we are loading them dynamically. In the fix, the components are loaded based on variant name. 
Tested by verifying the variants in vuepress docs in chrome browser.

fix(data-table): adding cell variants as dependency to table

---

packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/components/modal/modal.scss
packages/crayons-core/src/components/tooltip/readme.md

Fixes in this PR:
These are fixes suggested by design team. doc: https://docs.google.com/spreadsheets/d/1f8kTSWK2eTkAKCnW6-03ptRpqC2YigSe0gcdfuKwFTI/edit?usp=sharing
- Table row min height to 64px.
- Modal slider slide-in animation improved as suggested by design team.
- Changed from default tooltip to fw-tooltip inside DataTable.
Fixes were individually tested in Chrome browser.

fix(data-table): fw-tooltip on hovering over data-table row action buttons

---

packages/crayons-core/src/components/select/select.scss
packages/crayons-core/src/components/select/select.tsx

Modified the color of the state-text to match the state color.
Normal State:
Warning State:
Error State:

fix(fw-select): Modified the color of the state text based on the state

---

packages/crayons-core/src/components/datepicker/datepicker.scss
packages/crayons-core/src/components/input/input.scss
packages/crayons-core/src/components/select/select.scss

Standardised the height of fw-input, fw-select, fw-datepicker to 32px.

fix: standardized height of all input elements to 32px

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/datepicker/datepicker.scss
packages/crayons-core/src/components/datepicker/datepicker.tsx

- Added stateText prop and passed it to the fw-input.
- Moved the calendar icon inside the fw-input as slot.

feat(fw-datepicker): added stateText prop to the datepicker

---

packages/crayons-core/src/components/data-table/data-table.tsx

When localStorage permission is not available to the document where data-table is used, currently the document is throwing an error.
Adding a try catch before accessing the window.localStorage. If permission is not available, we show a warning saying that settings cannot be saved.

fix(data-table): adding localStorage permissions check before using it

---

packages/crayons-core/src/components/datepicker/datepicker.tsx
packages/crayons-core/src/components/select/select.tsx
packages/crayons-core/src/components/timepicker/timepicker.tsx

- Replace moment-mini with date-fns.

feat(timepicker): replace moment-mini with date-fns

---

packages/crayons-core/src/components/modal-title/modal-title.tsx
packages/crayons-core/src/components/modal/modal.tsx

Issue:
Even if title-text prop is empty, we are getting some empty space in UI for modal-header.
Fix: 
Display modal-header only if title-text prop has value in it.
Tested in Chrome browser. 
Tested with samples in Vuepress documentation.

fix(modal): display modal-title only when there is a title-text

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/data-table/custom-cells/icon/custom-cell-icon.tsx
packages/crayons-core/src/components/data-table/custom-cells/icon/readme.md

Able to pass a src directly to custom template icon variant.

feat(data-table): adding src prop to custom-cell-icon

---

packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.scss
packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/utils/types.ts

Added lock column configuration.
```html
<fw-data-table id="datatable-1" label="Data table 1" show-settings="true">
</fw-data-table>
<script type="application/javascript">
var datatable1 = document.getElementById('datatable-1');
datatable1.columns = [{
"key": "name",
"text": "Name",
"lock": true
}];
datatable1.rows = [{
"id": "0001",
"name": "Alexander Goodman"
}];
</script>
```
Tested with Chrome browser.

feat(data-table): adding a column lock configuration to data table

---

BREAKING.md
packages/crayons-core/src/components/select/select.tsx
packages/crayons-core/src/utils/index.ts

Disabled activating/opening select via the space bar button, so that user can search for space bar
BREAKING CHANGE: Disabled fw-select activation/open via space button

fix(fw-select): disabled select activation via space button

---

packages/crayons-core/src/components/data-table/data-table.tsx

Table settings input clearing on closing modal. 

feat(data-table): table settings input clearing on closing modal

---

packages/crayons-core/src/components/modal/modal.e2e.ts
packages/crayons-core/src/components/modal/modal.tsx

Issue:
Custom footer does not respond to changes in 'hideFooter' prop.
Fix:
We are using css display instead of removing the element from DOM. This enables to show to element when 'hideFooter' is set to true.

fix(modal): hideFooter prop working for custom footer

---

packages/crayons-core/src/components/tag/tag.tsx

Prevents the popup from opening on deleting the tag in multi-select
Before: 
https://user-images.githubusercontent.com/64781864/159431810-3538f143-8df0-4c00-b75a-520af325ed7e.mov
After:
https://user-images.githubusercontent.com/64781864/159431798-eb115718-8e60-4252-bbe9-fc5bbc762477.mov

fix(fw-select): prevents the dropdown from opening on option delete in multi-select

---

packages/crayons-core/src/components/data-table/data-table.scss

Issue:
Checkbox text when it has a longer word, does not wrap as expected.
Fix: 
Adding 'overflow-wrap: break-word' property to get results as expected.
Tested in Chrome, Firefox, Safari browsers.

fix(data-table): checkbox breaking word for overflowing text

---

packages/crayons-core/src/components/options-list/list-options.tsx
packages/crayons-core/src/components/select/select.tsx

When the user searches for a value and removes the searched value the popup will have the last showed options, it won't reset the filter and show 'notFoundText' instead of 'noDataText' - Fixed this issue

fix(fw-select): handled the empty text scenario in dynamic select

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/accordion-title/accordion-title.tsx
packages/crayons-core/src/components/accordion-title/readme.md
packages/crayons-core/src/components/accordion/readme.md

Added 3 variation of the accordion-header icon size

feat(fw-accordion-header): added prop for different icon size

---

packages/crayons-core/src/components/data-table/data-table.tsx

Issue:
When Datatable is removed from DOM, popperInstance was not destroyed. Popper instance was firing forUpdates on page actions like resize on an element that was not available in DOM.
Fix:
Destroy popperInstance on disconnectedCallback.

fix(data-table): removing popper instance once table is removed from dom

---

packages/crayons-core/src/components/checkbox/checkbox.scss

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break

fix(checkbox): handle checkbox label alignment if spanned multiple lines

---

packages/crayons-core/src/components/button-group/readme.md
packages/crayons-core/src/components/button/button.scss
packages/crayons-core/src/components/button/readme.md
packages/crayons-core/src/components/input/input.scss

added disabled border for secondary button
vertical aligned the icons button
replace primary with secondary buttons based on UX suggestion
Based on the UX suggestion modified icon size and removed min, full width buttons from docs
Removed focus animation for input
https://user-images.githubusercontent.com/64781864/161011004-eb3134ca-4b68-4a11-9dea-e238d2cb9224.mov

fix(fw-button): added disabled border for secondary button

---

packages/crayons-core/src/components/data-table/data-table.scss

fix(data-table): removing extra space from last rowActions button

---

packages/crayons-core/src/components/data-table/data-table.scss

fix(data-table): wrapping text in column when single word is big

---

packages/crayons-core/src/components/tab/tab.scss
packages/crayons-core/src/components/tabs/tabs.scss
styles/index.scss

Current Implementation:
After theming:
Code:
```
body {
--fw-tabs-padding-lr: 0px;
--fw-tabs-border-width: 0px;
--fw-tab-top-radius: 8px;
--fw-tab-margin-lr: 0px;
--fw-tab-padding-tb: 9px;
--fw-tab-padding-lr: 10px;
--fw-tab-border: #FFF;
--fw-tab-border-hover: #FFF;
--fw-tab-border-active: #EBEFF3;
--fw-tab-color: #576C7D;
--fw-tab-color-active: #384551;
--fw-tab-background: #FFF;
--fw-tab-background-active: #EBEFF3;
--fw-tab-weight: 500;
--fw-tab-weight-active: 500;
}
```

feat(tabs): adding necessary css variables to theme tabs

---

packages/crayons-core/src/components/data-table/data-table.tsx

Issue:
When width of columns is lesser than container space, table tends to auto computed width of columns to fit container. This is causing select column (with a fixed width in design) to expand too. 
Fix:
After render, check if select column width is auto computed. If so, manually remove last column width so that last column alone occupies entire table width.

feat(data-table): retaining width for select column

---

packages/crayons-core/src/components/modal/modal.scss
packages/crayons-core/src/components/toast-message/toast-message.scss

Issue:
Longer word makes toast message go out of the toast container.
Fix:
Breaking the longer word to fit in the container.

fix(toast): breaking longer word to fit into the toast container

---

packages/crayons-core/src/components/file-uploader/file/file-uploader-file.scss

In File uploader component, Increasing the font-weight for remove link in files list on designer's suggestion.

fix(file-uploader): font weight on remove link on files list updated

---

packages/crayons-core/src/components/options-list/list-options.tsx
packages/crayons-core/src/utils/index.ts

Fixed the `JSON.stringify` issue on the bigint data type by replace the existing comparison logic with the array and the `===` comparison.

fix(fw-select): fixed the serialize issue on bigint datatype

---

packages/crayons-core/src/components/data-table/custom-cells/paragraph/custom-cell-paragraph.scss
packages/crayons-core/src/components/data-table/custom-cells/paragraph/custom-cell-paragraph.tsx
packages/crayons-core/src/components/data-table/custom-cells/paragraph/readme.md
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/components/icon/readme.md
packages/crayons-i18n/i18n/en-US.json

Adding show more and show less to paragraph variant instead of icons.

fix(data-table): adding showmore/showless to paragraph variant

---

packages/crayons-core/src/components/popover/popover.tsx
packages/crayons-core/src/components/tooltip/tooltip.scss

Issue:
Not able to hover over tooltip content.
https://user-images.githubusercontent.com/61269786/164599586-f14f487a-eb0d-4d9f-b133-ded4b76cb122.mov
Fix: 
Issue was because we had hide on trigger leave. Now, changing mouseleave event to tooltip host and adding time to hide tooltip content so that people can move to tooltip content before the timeout/hide event.
https://user-images.githubusercontent.com/61269786/164599609-057f9a12-6612-4dfb-be7e-85bff238fc2a.mov
Tested in chrome browser.

fix(tooltip): ability to hover over tooltip content

---

packages/crayons-i18n/i18n/en-US.json

Changed 'show more' to 'Show more'. Requested by designer.

fix(data-table): capitalizing show more text in paragraph variant

---

packages/crayons-core/src/components/data-table/data-table.tsx

Issue:
- In cases where rows are re-rendered (when a row is deleted, filter is applied), contents move from one cell move to another. eg: 'show more' button on para variant moves to next cell.
https://user-images.githubusercontent.com/61269786/165032781-b3ee6560-ff46-4496-8f3f-3336197a0cc7.mov
Fix: 
- Adding key prop to table rows, solve this issue.
https://user-images.githubusercontent.com/61269786/165032831-96934ecb-7516-484b-9702-a5631a298aff.mov

fix(data-table): adding key to table row to avoid rendering issues

---

packages/crayons-core/src/components/select/select.tsx

Fix for the issue raised here - https://community.developers.freshworks.com/t/crayons-unable-to-update-fw-select-options-after-page-load/5555

feat(fw-select): added provision to add/update the options dynamically

---

packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/data-table/readme.md
packages/crayons-core/src/utils/types.ts

Currently there is no way to change styling on a column header.  In DSM, on one of the examples, note that there is padding left to the column name 'contact'.
In this PR, we are adding the ability to allow for customize table headers. 
```js
var columns = [{
"key": "createdby",
"text": "Created By",
"variant": "user",
"customHeader": (h, text) => {
return h('span', {'style': {'padding-left': '45px'}}, text)
}
}]
```
Before this feature,
After this feature,

feat(data-table): custom template for table headers

---

packages/crayons-core/package.json
packages/crayons-core/src/components/timepicker/readme.md
packages/crayons-core/src/components/timepicker/timepicker.e2e.ts
packages/crayons-core/src/components/timepicker/timepicker.tsx

- Fixed the example in the docs
- Improved the existing test cases and removed duplicate test case.
- removed the logic to set the `value` state in `fwChange` event to prevent the component re-render.

fix(fw-timepicker): fixed the documentation examples and improper loop

---

packages/crayons-core/src/components/select/select.scss

Fixed the CSS when the select width is <200px

fix(fw-select): prevented the css break

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/timepicker/readme.md
packages/crayons-core/src/components/timepicker/timepicker.e2e.ts
packages/crayons-core/src/components/timepicker/timepicker.scss
packages/crayons-core/src/components/timepicker/timepicker.tsx

- Exposed caret and optionsPlacement prop to control the position of the dropdown
- Removed the FieldControl as it is used in the fw-select.

feat(fw-timepicker): added placement option for the dropdown

---

packages/crayons-styles/scripts/convertTokens.js

Selector based css variables supports 
Instead of dumping all the css variables inside the root selector, the css variables are placed based on the component as shown below. This will help to overwrite global css variables at component level.
```
:root {
--fw-color-primary-600: #447093;
--fw-color-primary-700: #345c7c;
}
fw-button {
--fw-button-font-weight: 500;
--fw-button-font-size: 12px;
}
fw-tabs {
--fw-tabs-padding-left: 0px;
--fw-tabs-padding-right: 0px;
--fw-tabs-padding-lr: 0px;
}
```

feat(token builder): selector based tokens

---

packages/crayons-core/src/components/data-table/data-table.tsx
packages/crayons-core/src/components/datepicker/datepicker.tsx
packages/crayons-core/src/components/popover/popover.tsx
packages/crayons-core/src/utils/index.ts

Position of the popover modified with popper js custom modifier.
Before Fix:
After Fix:
Tested in Chrome, Firefox and Safari browsers.

fix(rtl): fixing popovers placement when direction is rtl

---

packages/crayons-core/src/components/country-phone/countries.json
packages/crayons-core/src/components/country-phone/country-phone.e2e.ts
packages/crayons-core/src/components/country-phone/country-phone.tsx

1. Resetting is breaking on country code select dropdown
2. Updated country code which was missing.
-> Tested Locally 
No impact

fix(country-phone): Resetting is breaking on country code select dropdown

---

packages/crayons-core/src/components/file-uploader/file-uploader.scss
packages/crayons-core/src/components/file-uploader/readme.md
packages/crayons-core/src/components/label/label.scss
packages/crayons-core/src/components/label/readme.md
packages/crayons-core/src/components/tabs/readme.md
packages/crayons-core/src/components/tabs/tabs.scss

BREAKING CHANGES:
1. renamed `--fw-tabs-margin-l` to `--fw-tabs-margin-inline-start` 
2. renamed `--fw-tabs-margin-r` to `--fw-tabs-margin-inline-end`
3. renamed `--fw-tabs-padding-left` to `--fw-tabs-padding-inline-start`
4. renamed `--fw-tabs-padding-right` to `--fw-tabs-padding-inline-end`

fix(css-variables): renamed css variables to keep it consistent with LTR and RTL support

---

packages/crayons-core/src/components/tooltip/tooltip.scss

Tooltip inherits properties for white space wrapping from its parent. In accordions case, there is a no-wrap for white space, which causes text inside tooltip to overflow. This PR fixes the issue.

fix(tooltip): text wrapping inherited from parent component

---

packages/crayons-core/src/components/input/input.scss

The change (adding transition to input) was added in #704 to animate border to blue on focus or hover.
When transition is applied for all properties, it inherits visibility property from parent and transition applies for visibility too. When trying to focus during visibility change, focus is not being applied to the component as it is considered to be invisible during visibility change. 
This is affecting crayons-internal editor popup components that use fw-input. When popup's visibility changes, 'setFocus' not working for 300ms as transition from visibility change stays in progress.

fix(input): transition only on border

---

packages/crayons-core/src/components/select/select.scss
packages/crayons-core/src/components/select/select.tsx

Issue mentioned in the document - [https://docs.google.com/spreadsheets/d/1bFQbT-lrnAvVNsneIBpHpibeAcpLvjscb3uPRUzFv4U/edit#gid=0](url)
Height of select is not constant. When a tag of avatar variant is added, the height of the select container is increased. This issue has been resolved in this PR.

fix: height of avatar variant of multi select

---

packages/crayons-core/src/components/radio-group/radio-group.tsx

Radio Group is allowing mulitple radio buttons to check instead of 1 active selection, Issue occured in Vue
https://user-images.githubusercontent.com/94836700/201891870-71df279a-c071-4d31-b8f7-9c93a766abd6.mov
Note : Works fine on React and JS

fix(component): existing selection Loop is not working in Vue Project

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/file-uploader/file-uploader.e2e.ts
packages/crayons-core/src/components/file-uploader/file-uploader.tsx
packages/crayons-core/src/components/file-uploader/readme.md
packages/crayons-core/src/utils/index.ts

https://github.com/freshworks/crayons/issues/716
**Description of the enhancement:**
Reset Method: add a reset method to make the component go back to the initial state.
getFiles: add a method to get the locally uploaded files from the component when part of a form.
There have been request from the community for the same.
https://community.freshworks.dev/t/file-uploader-how-to-reset/7282
https://community.freshworks.dev/t/how-to-use-fw-file-uploader/6881
We should be able to achieve something like,
```
const fileUploader = useRef(null);
const updateState = async (event) => {
event.preventDefault();
const files = await fileUploader.getFiles();
console.log(files);
fileUploader.reset();
};
```
```
<form onSubmit={(event) => updateState(event)}>
<FwFileUploader
name="sample-2" …
```

feat(file-uploader): adding reset and get files methods

---

packages/crayons-core/src/components/datepicker/datepicker.tsx

fix(datepicker): replace event.path with event.composedPath as it is deprecated from chrome 109 version

---

packages/crayons-core/src/components/data-table/data-table.e2e.ts
packages/crayons-core/src/components/data-table/data-table.tsx

When text inside column prop changes, the table settings are reset.
Solution:
Re-apply existing settings if there is no structural change in the new column definition.

fix(data-table): saved settings reset only on structural change

---

packages/crayons-core/src/components.d.ts
packages/crayons-core/src/components/textarea/readme.md
packages/crayons-core/src/components/textarea/textarea.e2e.ts
packages/crayons-core/src/components/textarea/textarea.tsx

feat(fw-textarea): added maxRows to fw-textarea for dynamic Resizing.
- Tested on local host with both variations with `rows` and `max-rows` and with just `max-rows` prop
- Eg: When rows=4 and max-rows=10, the default row size will be 4 and as the user interacts with textarea the row size will increase/decrease as the per the number of lines in the content.
- if no rows is set the default row size is considered as `2` which corresponds to the actual row size of the textarea when no rows prop is passed
- We also have an optional prop called `max-rows-debounce-timer` which can debounce the events callback to improve performance. Its default value is `200ms`

feat(fw-textarea): added maxRows to fw-textarea for dynamic Resizing

---

packages/crayons-core/src/components/datepicker/datepicker.tsx
packages/crayons-core/src/components/form/form.e2e.ts

To test the fix, Please use the below link. 
https://snazzy-blini-707dc6.netlify.app/components/core/form/#demo-dynamic-form
Test scenarios: Change the timezone to 
1. Canada (few hours behind) 
2. Russia (few hours ahead) 
3. current timezone.
Below fixes are made in the PR.
1. handled timezone offset calculation for datepicker when used in fw-form component

fix(datepicker): fix timezone offset issue for datepicker in form

---

packages/crayons-core/src/components/kebab-menu/kebab-menu.tsx
packages/crayons-core/src/components/select/select.tsx

Fix attribute conflict with addition of popover API introduced in chrome 114

fix(select, kebab-menu): Fix attribute conflict with addition of popover API introduced in chrome 114
