freshworks/crayons

- src/components/datepicker/datepicker.e2e.ts
- src/components/select/select.scss
- src/components/select/select.tsx
Fixed width for input element for multi-select
> fix(select.tsx, select.scss): fixed UI bugs for next line input

- src/components.d.ts
- src/components/datepicker/datepicker.stories.mdx
- src/components/datepicker/datepicker.tsx
- src/components/datepicker/readme.md
> [MP-7150] docs: date picker document

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement---.md
- .github/ISSUE_TEMPLATE/new-component-request---.md
- CONTRIBUTING.md
- src/components/datepicker/datepicker.e2e.ts
No changes in the code. So, the tests ran on pre-commit hook succeeded.
> docs(contribution.md, issue templates): fix lint errors on contribution.md and add issue templates

- src/.vuepress/components/DetailCard.vue
- src/.vuepress/components/LandingPage.vue
- src/.vuepress/constants.js
> docs: fixed freshworks logo and title font

- src/components/datepicker/datepicker.e2e.ts
- src/components/datepicker/readme.md
> [MP-7239] test: fix sporadic testcase failure

- .github/PULL_REQUEST_TEMPLATE.md
- src/components/datepicker/datepicker.e2e.ts
> [MP-7239] test: fix testcase failure

- src/components/datepicker/datepicker.tsx
- src/components/select/readme.md
> [MP-7554] fix: close popup on click outside

- src/components/datepicker/datepicker.e2e.ts
> [MP-7724] test: fix intermittent testcase failure

- package-lock.json
- package.json
- src/components/tabs/tabs.tsx
fwChange was firing twice. This fixes and makes it fire once.
fix #106
This has been tested locally on Storybook
> fix(fw-tabs): fwChange fires twice

- package-lock.json
- package.json
- All test cases passed in headless mode and on chromium
> [MP-7726] chore: update puppeteer version to fix sporadic test failure

- .storybook/preview.js
- src/components.d.ts
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/icon/readme.md
- src/components/modal/modal.e2e.ts
- src/components/modal/modal.scss
- src/components/modal/modal.stories.mdx
- src/components/modal/modal.tsx
- src/components/modal/readme.md
You can now use modals in your apps via Crayons. Modals are higly customizable overlays to help you
show data to your users in a focused way.
re #113
This has been tested locally with Storybook
> Introducing Modals to Crayons 🤩

- src/.vuepress/components/IconGallery.vue
> build: icon assets path change in vuepress

- src/components/select/select.tsx
Disable all tags if multi select is disabled
fix #137
> fix(select): fixed tag not getting disabled

- src/components/datepicker/datepicker.tsx
- src/index.html
> fix: fix datapicker false events trigger

- src/components/dropdown-button/readme.md
> docs(dropdown button): dropdown button docs added

- .gitignore
- gulpfile.js
- package-lock.json
- package.json
- src/components/icon/icon.tsx
- tsconfig.json
Icons url path is fetched wrongly and icons are not displayed
fix #143
Tested it by serving the built library in local
> fix(icon): fixes icon url path error

- src/components/textarea/readme.md
- src/components/textarea/textarea.scss
- src/index.html
introduced text color for textarea as scss var
fix #152
npm run local with changes in `index.html`
> feat(textarea): introduced text color for textarea as scss var

- gulpfile.js
- src/components/icon/icon.tsx
- src/components/select/select.tsx
> fix(select.tsx): fixed placeholder problem in select

- src/components/input/input.scss
- src/components/textarea/textarea.scss
- src/index.html
- src/styles/_theme.scss
fix #161 
Tested it by serving the built library in local
> style: fix disabled input text color

- packages/crayons-core/src/components/button/button.scss
- packages/crayons-core/src/components/checkbox/checkbox.scss
- packages/crayons-core/src/components/dropdown-button/dropdown-button.scss
- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/radio/radio.scss
- packages/crayons-core/src/components/select-option/select-option.scss
- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/textarea/textarea.scss
- packages/crayons-core/src/components/toggle/toggle.scss
- packages/crayons-core/src/index.html
- packages/crayons-core/src/styles/index.scss
> replacing css variables with sass variables

- .npmrc
Make version check strict as dependency resolving is not happening properly with older versions of
npm and as a result build fails
> chore: make node and npm version checks strict

- package-lock.json
- package.json
- packages/crayons-core/package.json
- packages/crayons-datatable/package.json
> chore: kill running port before starting a11y test

- packages/crayons-core/src/components/tab-panel/readme.md
- packages/crayons-core/src/components/tab/readme.md
- packages/crayons-core/src/components/tabs/readme.md
Have verified the generated readme
> docs(tabs): update tabs readme with recent changes

- package-lock.json
- packages/crayons-core/package.json
- packages/crayons-datatable/package.json
> Lock @stencil/core version to 2.9.0

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/popover/popover.tsx
- packages/crayons-core/src/components/popover/readme.md
- added more placement options to popover and updated the placement for datepicker
> fix(fw-datepicker): Fixed the improper datepicker placement

- packages/crayons-core/src/components/options-list/readme.md
- packages/crayons-core/src/components/popover/readme.md
- packages/crayons-core/src/components/select/readme.md
added usage documentation for fw-popover and fw-list-options
> docs(fw-popover and fw-list-options): added usage documentation

- packages/crayons-core/src/components/button/readme.md
- packages/crayons-core/src/components/checkbox/readme.md
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/dropdown-button/readme.md
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/input/readme.md
- packages/crayons-core/src/components/label/readme.md
- packages/crayons-core/src/components/modal/readme.md
- packages/crayons-core/src/components/radio-group/readme.md
- packages/crayons-core/src/components/radio/readme.md
- packages/crayons-core/src/components/select-option/readme.md
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/spinner/readme.md
- packages/crayons-core/src/components/tab-panel/readme.md
- packages/crayons-core/src/components/tab/readme.md
- packages/crayons-core/src/components/tabs/readme.md
- packages/crayons-core/src/components/tag/readme.md
- packages/crayons-core/src/components/textarea/readme.md
- packages/crayons-core/src/components/timepicker/readme.md
- packages/crayons-core/src/components/toast/readme.md
- packages/crayons-core/src/components/toggle/readme.md
- packages/crayons-datatable/src/components/button1/readme.md
> docs(react samples): added react samples in the readme for components

- packages/crayons-core/src/components/radio-group/radio-group.tsx
This is tested by rendering the component in the CRA for react o/p target and verified it for web component by rendering it in index.html
> fix(radio-group): fix radio group to be compatiable with react version

- packages/crayons-core/src/components/button/readme.md
Verified the changes the generated docs locally
> docs(button): fix usage of label

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/toggle/readme.md
- packages/crayons-core/src/components/toggle/toggle.tsx
Have verified by rendering component in index.html
> feat(toggle): show icon for toggle by default

- packages/crayons-core/src/components/popover/popover.tsx
> fix(fw-popover): null check

- package-lock.json
- packages/crayons-core/CHANGELOG.md
- packages/crayons-core/package.json
- packages/crayons-datatable/CHANGELOG.md
- packages/crayons-datatable/package.json
> docs(changelog): Changelog update

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/avatar/avatar.e2e.ts
- packages/crayons-core/src/components/avatar/avatar.scss
- packages/crayons-core/src/components/avatar/avatar.stories.mdx
- packages/crayons-core/src/components/avatar/avatar.tsx
- packages/crayons-core/src/components/avatar/readme.md
- packages/crayons-core/src/index.html
- styles/variables/_colors.scss
> Avatar canary2

- packages/crayons-core/src/components/button-group/readme.md
- packages/crayons-core/src/components/modal/readme.md
- packages/crayons-core/src/components/select-option/readme.md
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/global/crayons.ts
> docs(code-samples): update code samples in readme

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/tab/readme.md
- packages/crayons-core/src/components/tab/tab.tsx
- packages/crayons-core/src/components/tabs/readme.md
> fix(tab): fix fw-tab to work with react typescript

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/avatar/avatar.scss
- packages/crayons-core/src/components/avatar/avatar.tsx
- packages/crayons-core/src/components/avatar/readme.md
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/tag/readme.md
- packages/crayons-core/src/components/tag/tag.scss
- packages/crayons-core/src/components/tag/tag.tsx
- packages/crayons-core/src/components/timepicker/readme.md
> feat(fw-tag): added avatar variant for tag

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/toast-message/readme.md
- packages/crayons-core/src/components/toast-message/toast-message.tsx
- packages/crayons-core/src/components/toast/readme.md
- packages/crayons-core/src/components/toast/toast-util.ts
Tested the code samples to be working fine in the docs site
> docs(toast): update code samples with toastoptions interface for reference

- packages/crayons-core/CHANGELOG.md
> docs(changelog): update changelog with correct breaking change

- .eslintrc.js
- packages/crayons-core/src/components/button-group/button-group.e2e.ts
- packages/crayons-core/src/components/modal/modal.tsx
- packages/crayons-core/src/utils/index.ts
- packages/crayons-icon/gulpfile.js
- www/scripts/reorganize.js
> chore(eslint-config): Enable Strict type checking via Eslint

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/tag/readme.md
- packages/crayons-core/src/components/tag/tag.e2e.ts
- packages/crayons-core/src/components/tag/tag.tsx
- packages/crayons-core/src/components/timepicker/readme.md
- packages/crayons-core/src/index.html
> feat(fw-tag): tags can be removed via backspace

- packages/crayons-core/src/components/button/readme.md
- www/.vuepress/config.js
- www/frameworks/react/readme.md
> docs(react-docs): docs for using react with crayons

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/tag/readme.md
- packages/crayons-core/src/components/tag/tag.tsx
> feat(fw-tag): added focusable prop and setFocus method

- packages/crayons-core/src/components/options-list/list-options.tsx
> feat(fw-list-options): scroll to the last selected item on open

- packages/crayons-core/src/components/select/readme.md
> docs(fw-select): added react examples

- packages/crayons-core/src/components/select/readme.md
> docs(fw-select): added doc for dynamic search

- packages/crayons-core/src/components/checkbox/checkbox.scss
> style(checkbox): fix checkbox styles

- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/input/input.tsx
> fix(fw-input): adjust input styles for icons

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/button/button.tsx
- packages/crayons-core/src/components/button/readme.md
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/popover/popover.tsx
- packages/crayons-core/src/components/popover/readme.md
- packages/crayons-core/src/components/select-option/select-option.scss
- packages/crayons-core/src/components/select-option/select-option.tsx
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/select/select.tsx
- packages/crayons-core/src/components/tag/tag.scss
- packages/crayons-core/src/components/timepicker/readme.md
> feat(fw-popover): added prop to focus on the content

- styles/_utils.scss
- styles/mixins/_border.scss
- www/.vuepress/config.js
- www/css-utils/border/readme.md
- www/css-utils/color/readme.md
> feat(css-utils): adding utils for border and font colors

- packages/crayons-core/src/components/select/readme.md
> docs: fixed readme styling

- packages/crayons-core/src/components/modal/readme.md
> docs(modal): react ref sample

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/toggle-group-button/readme.md
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.e2e.ts
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.scss
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.tsx
- packages/crayons-core/src/components/toggle-group/readme.md
- packages/crayons-core/src/components/toggle-group/toggle-group.e2e.ts
- packages/crayons-core/src/components/toggle-group/toggle-group.scss
- packages/crayons-core/src/components/toggle-group/toggle-group.tsx
- packages/crayons-core/src/index.html
- packages/crayons-core/src/utils/list-utils.spec.ts
- packages/crayons-core/src/utils/list-utils.ts
> feat(toggle-group): Toggle group button supporting multiple selection

- packages/crayons-core/src/components/toggle-group-button/readme.md
- packages/crayons-core/src/components/toggle-group/readme.md
> docs(toggle-group): code samples for toggle-group

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): add stopImmediatePropagation and refactor code

- styles/_utils.scss
- www/.vuepress/config.js
- www/css-utils/color/readme.md
- www/css-utils/examples/readme.md
> docs(css-utils): adding examples using css utils

- packages/crayons-core/src/utils/list-utils.spec.ts
> chore(test-toggle-group): remove unused imports

- package-lock.json
- packages/crayons-core/package.json
> chore(deps): remove webpack peer dependency

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/avatar/avatar.e2e.ts
- packages/crayons-core/src/components/avatar/avatar.tsx
- packages/crayons-core/src/components/avatar/readme.md
- packages/crayons-core/src/components/data-table/custom-cells/anchor/custom-cell-anchor.scss
- packages/crayons-core/src/components/data-table/custom-cells/anchor/custom-cell-anchor.tsx
- packages/crayons-core/src/components/data-table/custom-cells/anchor/readme.md
- packages/crayons-core/src/components/data-table/custom-cells/user/custom-cell-user.scss
- packages/crayons-core/src/components/data-table/custom-cells/user/custom-cell-user.tsx
- packages/crayons-core/src/components/data-table/custom-cells/user/readme.md
- packages/crayons-core/src/components/data-table/data-table.e2e.ts
- packages/crayons-core/src/components/data-table/data-table.tsx
- packages/crayons-core/src/components/data-table/readme.md
- packages/crayons-core/src/utils/types.ts
- styles/_utils.scss
- styles/mixins/_typography.scss
- www/css-utils/typography/readme.md
1. Anchor<img width="767" alt="Anchor table" src="https://user-images.githubusercontent.com/61269786/146703413-1d88faa1-4479-45d6-91ba-6d05ca15b8ac.png">
2. User<img width="760" alt="User" src="https://user-images.githubusercontent.com/61269786/146703599-6b33fca6-d3c3-4231-b46b-85f6299af4ee.png">
```js
let columns =  [{
"key": "user",
"text": "User",
"orderIndex": 1,
"variant": "user"
}, {
"key": "search",
"text": "Preferred Search Engine",
"orderIndex": 2,
"variant": "anchor"
}];
let rows = [{
"id": "001",
"search": { "text": "Google", "href": "https://www.google.com" },
"createdby": { 
"image": "https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=300&q=80",
"name": "Alexander Goodman", …
```
> feat(data-table): custom cell implementation

- packages/crayons-core/src/components/checkbox/checkbox.e2e.ts
- packages/crayons-core/src/components/checkbox/checkbox.scss
- packages/crayons-core/src/components/checkbox/checkbox.tsx
> Fix checkbox font weight

- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/select/select.tsx
> fix(fw-select): handled undefined / invalid value scenarios

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/tabs/readme.md
- packages/crayons-core/src/components/tabs/tabs.tsx
> feat(tabs): expose public method to set active tab index from outside of fw-tabs

- packages/crayons-core/src/components/toast-message/toast-message.scss
> fix(fw-toast): added box shadow to toast message

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/menu-item/menu-item.scss
- packages/crayons-core/src/components/menu-item/menu-item.tsx
- packages/crayons-core/src/components/menu-item/readme.md
- packages/crayons-core/src/components/menu/menu.scss
- packages/crayons-core/src/components/menu/menu.tsx
- packages/crayons-core/src/components/menu/readme.md
> feat(fw-menu): added menu and menu-item

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/select/select.tsx
> style(fw-select): added css variables to the select component

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/drag-item/drag-item.tsx
- packages/crayons-core/src/components/drag-item/readme.md
- packages/crayons-core/src/utils/draggable.ts
> feat(fw-drag-item): added feature to pin the position of fw-drag-item

- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/input/readme.md
- packages/crayons-core/src/components/tabs/readme.md
- packages/crayons-core/src/components/tabs/tabs.scss
- packages/crayons-core/src/components/tabs/tabs.tsx
> feat(input): expose css variables for margin and padding for input, tabs

- packages/crayons-core/src/components/drag-container/readme.md
- packages/crayons-core/src/utils/draggable.ts
> fix(fw-drag-container): drag container now supports dynamic and nested child items 

- packages/crayons-core/src/components/data-table/custom-cells/anchor/custom-cell-anchor.scss
- packages/crayons-core/src/components/data-table/custom-cells/user/custom-cell-user.scss
- packages/crayons-core/src/components/data-table/data-table.e2e.ts
- packages/crayons-core/src/components/data-table/data-table.scss
- packages/crayons-core/src/components/data-table/data-table.tsx
- packages/crayons-core/src/components/data-table/readme.md
- packages/crayons-core/src/utils/types.ts
- Column hide
- Setting width properties (min-width, width and max-width) to a column
- Formatting data (Array->String, ISOTimeFormat->ReadableString) before rendering to table cell.
- Safari fix for event.path missing
_Kindly review the PR as individual commits as this PR consists of changes across 7 files._
```js
const columns = [{
"key": "role",
"text": "Role",
"hide": true
}]
```
```js
const columns = [{
"key": "role",
"text": "Role",
"widthProperties": {
"width": "200px"
}
}];
```
```js
columns: [{
"key": "courses",
"text": "Courses",
"formatData": (courses) => {
return courses.join(', ');
}
}, {
"key": "appliedon",
"text": "Applied on",
"formatData": (ISOString) => {
const date = new Date(ISOString);
return date.getDate() + " " + months[date.getMonth()] + ", " + date.getFullYear(); …
```
> feat(data-table): adding column hide, column width, data formatting features for DataTables.

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/tag/readme.md
- packages/crayons-core/src/components/tag/tag.tsx
> fix(fw-tag): removed reflect for value and added int support

- packages/crayons-core/src/components/tab-panel/tab-panel.tsx
- packages/crayons-core/src/components/tab/tab.tsx
- packages/crayons-core/src/components/tabs/tabs.tsx
- Fix incorrect key press handling in tabs.
- Accommodate subtree changes in mutation observer.
> fix(tabs): fix incorrect key press handling in tabs and accommodate child attrs

- packages/crayons-core/src/components/accordion-title/accordion-title.scss
> fix(accordion): added pointed cursor to accordion title

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- Fix datepicker month year update handling
> fix(datepicker): fix datepicker month/year updates

- packages/crayons-core/src/components/toast-message/toast-message.scss
- packages/crayons-core/src/components/toast-message/toast-message.tsx
> fix(fw-toast-message): updated styles for toast-message

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/label/label.scss
- packages/crayons-core/src/components/modal-content/modal-content.scss
- packages/crayons-core/src/components/modal-title/modal-title.scss
- packages/crayons-core/src/components/modal-title/modal-title.tsx
- packages/crayons-core/src/components/modal/modal.scss
- packages/crayons-core/src/components/modal/modal.tsx
- packages/crayons-core/src/components/modal/readme.md
- packages/crayons-core/src/components/toggle-group-button/readme.md
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.e2e.ts
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.tsx
> fix(component-style-fixes): modal style, label style, toggle icon button fixes as per DSM

- packages/crayons-core/src/components/tabs/tabs.scss
> fix(tabs): remove vertical scrollbar for tabs nav

- packages/crayons-core/src/components/tag/tag.scss
- packages/crayons-core/src/components/tag/tag.tsx
- Modified the style of fw-tag based on the DSM
**Crayons: Normal Tag**
**DSM : Normal Tag**
**Crayons: Avatar Tag**
**DSM : Avatar Tag**
> fix(fw-tag): fixed the style based on DSM

- packages/crayons-core/src/components/checkbox/checkbox.scss
- packages/crayons-core/src/components/checkbox/checkbox.tsx
- packages/crayons-core/src/components/checkbox/readme.md
- packages/crayons-core/src/components/data-table/readme.md
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/dropdown-button/readme.md
- packages/crayons-core/src/components/form-control/readme.md
- packages/crayons-core/src/components/form/readme.md
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-core/src/components/options-list/readme.md
- packages/crayons-core/src/components/select-option/readme.md
- packages/crayons-core/src/components/select/readme.md
- packages/crayons-core/src/components/timepicker/readme.md
Screenshot with the changes applied:
> fix(checkbox): fix checkbox styles based on style guide

- packages/crayons-core/src/components/accordion/accordion.tsx
- packages/crayons-core/src/components/accordion/readme.md
> fix(accordion): add watcher for expanded attribute

- packages/crayons-core/src/components/checkbox/checkbox.scss
- packages/crayons-core/src/components/checkbox/checkbox.tsx
> fix(checkbox): fix checkbox disabled state color

- packages/crayons-core/src/components/input/input.scss
> fix(fw-input): fixed the transparent background color of input

- packages/crayons-core/src/components/checkbox/checkbox.scss
- packages/crayons-core/src/components/checkbox/checkbox.tsx
> fix(checkbox): fix cursor style for disabled state

- packages/crayons-core/package.json
> chore: adding yup as peer dependency

- package-lock.json
> chore(yup): update peer deps for yup

- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/input/input.tsx
> fix(fw-input): fixed the flex-flow bug when width is <= 200px

- packages/crayons-core/src/components/select/select.scss
- Increased the label font weight to 600
- Increased the label line height to 20px
> style(fw-select): changed label based on DSM

- packages/crayons-core/src/components/data-table/data-table.scss
- packages/crayons-core/src/components/data-table/data-table.tsx
- Table settings fixed at right corner of table when there is a horizontal scroll on the table.
- Table shimmer hiding when table has rows on initial render.
- Hide settings when table isLoading.
Tested in Chrome, Safari, Firefox browsers.
Tested in vuepress documentation samples.
> fix(data-table): fix for table setting moving on horizontal scroll

- packages/crayons-core/src/components/input/input.scss
> fix(fw-input): fixed the hint/error text padding

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): fix datepicker behaviour after event standardisation

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/checkbox/checkbox.tsx
- packages/crayons-core/src/components/checkbox/readme.md
- packages/crayons-core/src/components/data-table/data-table.tsx
- packages/crayons-core/src/components/input/input.tsx
- packages/crayons-core/src/components/popover/readme.md
Updated the components to follow event standards.
Comparsion with the `next` branch event conventions
| Component |  Before | After |
| ------------ | ------------- | ------------- | 
| fw-input | fwInputClear.emit()  | fwInputClear.emit({ event, name, value })  |
> fix(event-changes): updated the components to follow event standards

- packages/crayons-core/src/components/input/input.tsx
> fix(fw-input): fix fw-input cursor resetting on typing `.` for decimal input

- packages/crayons-core/src/components/datepicker/datepicker.scss
- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): fix blur event emit and trigger for show datepicker popup

- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/form-control/readme.md
- packages/crayons-core/src/components/form/readme.md
- packages/crayons-core/src/components/icon/readme.md
> docs(readme): updated auto generated readme files

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/form/form-util.ts
> fix(fw-datepicker): handle cancel and popover hide usecase and added readonly prop

- packages/crayons-core/src/components/form/readme.md
> docs(fw-form): updated code samples for dynamic form

- package-lock.json
- packages/crayons-core/package.json
- packages/crayons-i18n/package.json
- packages/crayons-i18n/src/Translation.ts
> chore(i18n-deps): added stencil/store and date-fns as dependencies

- packages/crayons-i18n/i18n/en.js
> chore(i18n-strings): updated i18n strings for form-builder

- packages/crayons-i18n/i18n/en.js
> chore(i18n-strings): updated i18n strings for form builder

- packages/crayons-i18n/i18n/en.js
> chore(platform-ui): added strings for filters and searchdropdown in platform-ui

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/dropdown-button/dropdown-button.tsx
- packages/crayons-core/src/components/modal-footer/modal-footer.tsx
- packages/crayons-core/src/components/modal/modal.tsx
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/pagination/pagination.tsx
- packages/crayons-core/src/components/select/select.tsx
- packages/crayons-i18n/i18n/de.js
- packages/crayons-i18n/src/Translation.ts
> feat(i18n): remove default value being passed to decorator

- packages/crayons-i18n/i18n/en.js
> chore(i18n-fileuploader): added i18n strings for file uploader

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- Fixes popover trigger issue introduced by https://github.com/freshworks/crayons/pull/448
> fix(datepicker): fix datepicker for popover trigger

- .github/workflows/check.yml
- .github/workflows/main.yml
- package.json
- packages/crayons-core/src/components/format-date/format-date.e2e.ts
- packages/crayons-core/src/function-components/field-control.tsx
- packages/crayons-icon/bin/index.cli.js
> refactor(field-control): update prop comments

- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/form/form-util.ts
- packages/crayons-core/src/components/form/form.tsx
- packages/crayons-core/src/components/pagination/pagination.tsx
- packages/crayons-i18n/src/Translation.ts
> feat(i18n-date-fns): dynamically load date-fns lang module and interpolation related changes

- BREAKING.md
> docs(breaking.md): update breaking changes for radio-group, tab and tabs

- BREAKING.md
> docs(breaking-changes): updated breaking changes doc

- BREAKING.md
> docs(modal): adding breaking changes for modal

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): make div inline-flex to occupy only width of contents

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/form/form.tsx
> fix(fw-form): handle blur validation for form and fix selected year for datepicker

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/options-list/readme.md
> docs(list-options): fix list-options code sample and type cast min and max year as number

- packages/crayons-i18n/i18n/en.json
> feat(filter-i18n): updated the value based on the new UI

- packages/crayons-i18n/src/Translation.ts
- www/utilities/i18n/readme.md
> fix(i18n-pluralize): added pluralize util as part of crayons-i18n package

- Jenkinsfile
> chore(jenkinsfile): update correct paths in Jenkins file for v3

- package-lock.json
- package.json
> chore(package.json): update correct version for engines

- BREAKING.md
> docs(fw-select): added multiselect breaking condition

- www/introduction/migrating-to-v3/readme.md
> docs(breaking.md): update breaking changes guide url

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/accordion-title/accordion-title.tsx
- packages/crayons-core/src/components/accordion-title/readme.md
- packages/crayons-core/src/components/accordion/readme.md
Reverts freshworks/crayons#500
> Revert "feat(fw-accordion-header): added prop for different icon size"

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/accordion-title/accordion-title.tsx
- packages/crayons-core/src/components/accordion-title/readme.md
- packages/crayons-core/src/components/accordion/readme.md
> feat(fw-accordion-header): added prop for different icon size

- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/select/select.tsx
- Clear single select by clearing input
- Fixed the focus issue in select.
> feat(fw-select): clear single select by clearing input

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/select/select.tsx
> fix(datepicker): emit fwchange on clearing input

- packages/crayons-core/src/components/select/select.scss
> style(fw-select): moved the caret position in select

- package-lock.json
> fix(package-lock): update lock file

- package-lock.json
> fix(package-lock): update lock file (#534)

- package-lock.json
- packages/crayons-core/CHANGELOG.md
- packages/crayons-core/package.json
- packages/crayons-core/src/components/data-table/data-table.tsx
> chore(release): merge next to master

- packages/crayons-core/src/components/data-table/data-table.scss
- packages/crayons-core/src/components/modal-title/modal-title.scss
- packages/crayons-core/src/components/modal/modal.tsx
Fixes in this PR:
- Modal close button change as per DSM.
- Table settings Drag item padding fix.
This has been tested in Chrome.
> Modal Datatable UI fixes

- packages/crayons-core/src/components/data-table/data-table.scss
> fix(data-table): checkbox hover style visible in table settings

- packages/crayons-i18n/.gitignore
- packages/crayons-i18n/scripts/crowdin.js
- packages/crayons-i18n/src/Translation.ts
> fix(crayons): fix local setup

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/datepicker/readme.md
> feat(datepicker): expose public method to clear input

- packages/crayons-core/src/components/options-list/list-options.tsx
> fix(fw-select): added bigint data type support

- www/introduction/migrating-to-v3/readme.md
- www/introduction/readme.md
> fix(docs): fix link for icon

- styles/index.scss
- www/css-utils/typography/readme.md
> feat(font-family): adding ability to change font family on components

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): handle datepicker input clear

- packages/crayons-core/src/components/avatar/avatar.scss
- packages/crayons-core/src/components/avatar/avatar.tsx
- styles/variables/_colors.scss
> fix(avatar-fix): DSM style fixes for intials with different modes

- packages/crayons-core/src/components/form/form-util.ts
> fix(serialize-form): handle null for date field while serializing form

- packages/crayons-core/src/components/select/select.scss
> fix(select): select input font inherits from parent

- packages/crayons-i18n/i18n/en-US.json
> chore(i18n): updated i18n string

- packages/crayons-core/src/components/form/readme.md
- www/introduction/readme.md
> docs(form): update docs for form to have form schema section

- CONTRIBUTING.md
> docs(contribution.md): updated local environment setup steps

- packages/crayons-core/src/components/form-control/form-control.tsx
> fix(form-control): remove hard-coded readonly property for date-picker

- packages/crayons-i18n/i18n/en-US.json
> chore(i18n-changes): add i18n string for platformuiwidget

- packages/crayons-core/src/components/select/select.tsx
> fix(fw-select): prevented the mutation of option

- packages/crayons-i18n/i18n/en-US.json
> chore(i18n-string): updated i18n string

- package.json
> chore(package.json): use no-verify while publishing next version

- .github/workflows/release-next.yml
> Adding workflow for next release

- packages/crayons-core/src/components/pill/pill.e2e.ts
- packages/crayons-core/src/components/pill/pill.tsx
> fix(fw-pill): update component style on changing color prop

- packages/crayons-core/src/components/radio-group/radio-group.e2e.ts
- packages/crayons-core/src/components/radio-group/radio-group.tsx
- packages/crayons-core/src/components/radio/radio.tsx
> fix(radio-group): a11y changes for radio-group

- packages/crayons-core/src/components/data-table/custom-cells/paragraph/custom-cell-paragraph.scss
- packages/crayons-core/src/components/data-table/custom-cells/user/custom-cell-user.scss
- packages/crayons-core/src/components/data-table/data-table.scss
- packages/crayons-core/src/components/datepicker/datepicker.scss
- packages/crayons-core/src/components/drag-item/drag-item.scss
Typography and colors variables updated in below components.
1. Data-table
2. Datepicker
3. Drag-item
> feat(theming): updating size, color on data-table, datepicker, drag-item

- packages/crayons-core/src/components/form/readme.md
> docs(form): update docs to use crayons components

- packages/crayons-core/src/components/checkbox/checkbox.tsx
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/input/input.tsx
- packages/crayons-core/src/components/radio-group/radio-group.tsx
- packages/crayons-core/src/components/select/select.tsx
- packages/crayons-core/src/components/textarea/textarea.tsx
- packages/crayons-core/src/components/timepicker/timepicker.tsx
> chore(input-controls): rename handleSlotChange to checkSlotContent, added slotChange for formcontrol

- packages/crayons-core/src/components/tabs/tabs.tsx
- packages/crayons-core/src/index.html
> fix(tabs): fix handling index

- packages/crayons-core/src/components/datepicker/datepicker.scss
- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/tag/tag.scss
- packages/crayons-core/src/components/textarea/textarea.scss
- packages/crayons-core/src/function-components/field-control.scss
- styles/_theme.scss
- styles/variables/_colors.scss
Please refer the [Status and Color change info sheets](https://docs.google.com/spreadsheets/d/1IeDWg0Jd1Y8ThUl10oCHGl7F4Pg-3Zy3FGGrzG6hbk0/edit#gid=1759052472) for reference.
> feat(theming): update color codes of components

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): handle min and max dates when passed

- .github/workflows/release-next.yml
> chore(workflow): fix workflow to avoid secrets in if condition

- .github/workflows/release-latest.yml
- .github/workflows/release-next.yml
> chore(workflow): avoid checks in workflows

- packages/crayons-core/src/components/button/button.scss
- packages/crayons-core/src/components/file-uploader/file-uploader.scss
- packages/crayons-core/src/components/radio/radio.scss
- packages/crayons-core/src/function-components/field-control.scss
Fixed following items in this PR:
- disabled button text color
- file-uploader hint text size
- Form mandatory star size
- Radio disabled color
> fix(theming): fixing file uploader hint size

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): fix setMonth for last dates

- packages/crayons-core/package.json
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/modal/modal.tsx
- packages/crayons-core/src/components/toggle/toggle.tsx
- packages/crayons-core/src/utils/index.ts
- packages/crayons-core/stencil.config.ts
In this PR:
- Adding RTLCSS plugin.
- Adding dir attribute for components that use CSS properties that don't have equal logical props.
Tested in Chrome, Firefox and Safari.
> feat(rtl): adding rtlcss plugin

- www/.vuepress/constants.js
> docs(sample-url): updated github sample url in the docs

- packages/crayons-core/src/components/inline-message/inline-message.scss
- packages/crayons-core/src/components/inline-message/inline-message.tsx
- packages/crayons-core/src/components/radio/radio.e2e.ts
- packages/crayons-core/src/components/radio/radio.scss
- packages/crayons-core/src/components/radio/radio.tsx
- packages/crayons-i18n/i18n/en-US.json
> chore(co-export): i18n strings for coui export, style fixes for inline-message and radio component

- packages/crayons-core/src/components/checkbox/checkbox.scss
> fix(checkbox-style-fix): checkbox vertical align style fix

- packages/crayons-core/src/components/inline-message/inline-message.scss
- packages/crayons-core/src/components/inline-message/readme.md
- packages/crayons-styles/design-tokens/freshsales.json
- packages/crayons-styles/package-lock.json
- packages/crayons-styles/package.json
- packages/crayons-styles/src/index.js
> feat(theming): update inline banner component

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/form/form-declaration.ts
- packages/crayons-core/src/components/form/form.tsx
- packages/crayons-core/src/components/form/readme.md
> feat(fw-form): Add a method to get form values

- packages/crayons-i18n/i18n/en-US.json
> chore(co-export-i18n): added i18n string for coui export

- www/css-utils/examples/readme.md
> fix(css-utils): improve examples documentation

- packages/crayons-core/src/components/checkbox/checkbox.scss
> fix(checkbox): align check icon within checkbox

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/datepicker/readme.md
> fix(datepicker): handle min date, max date

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): emit ISO formatted string

- packages/crayons-core/src/components/button/button.tsx
> fix(button): handle onClick on disabled

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/icon/icon.tsx
- packages/crayons-core/src/components/icon/readme.md
> chore(icon-fix): added url prop, added watchers for dataSvg and url

- www/introduction/readme.md
> docs(installation): update the path to crayons.js

- packages/crayons-extended/custom-objects/src/components/export/readme.md
- packages/crayons-extended/custom-objects/src/components/form-builder/readme.md
> fix(form-builder): fixed field add and search bug in form builder implementation

- packages/crayons-core/src/components/button/button.scss
- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/input/readme.md
- packages/crayons-core/src/components/label/label.scss
- packages/crayons-core/src/components/modal-footer/modal-footer.scss
- packages/crayons-core/src/components/options-list/list-options.scss
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/pill/pill.scss
- packages/crayons-core/src/components/select-option/select-option.scss
- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/tag/tag.scss
- packages/crayons-core/src/components/textarea/textarea.scss
- packages/crayons-core/src/components/toast-message/readme.md
- packages/crayons-core/src/components/toast-message/toast-message.scss
- packages/crayons-core/src/components/toast-message/toast-message.tsx
- packages/crayons-core/src/components/toast/readme.md
- packages/crayons-core/src/index.html
- packages/crayons-core/stencil.config.ts
- styles/variables/_colors.scss
- styles/variables/_typography.scss
> fix(styles): style fixes as per Freshworks DSM

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> refactor(datepicker): remove unnecessary attributes to select

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/select/select.tsx
> feat(select): prevent the options from being clipped when placed in a container with overflow:auto|hidden|scroll

- packages/crayons-core/stencil.config.ts
- packages/crayons-extended/custom-objects/stencil.config.ts
> build(stencil-config): set autoDefineCustomElements:false to fix scoping error with treeshaking build

- packages/crayons-core/src/components/country-phone/country-phone.e2e.ts
> test: fix failing tests

- packages/crayons-core/src/components/select/select.tsx
> fix: select - cleanup unused state and remove warnings

- packages/crayons-core/src/components/popover/popover.tsx
> fix: popper position when popper content dynamically change

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/data-table/custom-cells/anchor/custom-cell-anchor.tsx
- packages/crayons-core/src/components/data-table/custom-cells/anchor/readme.md
- packages/crayons-core/src/components/data-table/readme.md
> feat(data-table): add target property for nav link custom cell

- BREAKING.md
- packages/crayons-core/CHANGELOG.md
- www/.vuepress/config.js
- www/css-utils/installation/readme.md
- www/introduction/migrating-to-v4/readme.md
> docs(breaking.md): update migration guide and breaking changes doc

- www/.vuepress/config.js
- www/introduction/migrating-to-v4/readme.md
> docs(introduction): update v4 introduction

- packages/crayons-core/src/components/select/select.tsx
> fix: border of button variant

- packages/crayons-core/src/components/file-uploader/readme.md
docs: event name string change in file-uploader component filesUploaded > fwFilesUploaded.
Reference: https://community.freshworks.dev/t/file-uploader-fw-file-uploader-fix-needed/6966
Local
> docs: event name string change in file-uploader component

- src/components/readme.md
> docs(introduction): fix links

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/tabs/readme.md
- packages/crayons-core/src/components/tabs/tabs.tsx
Fixes: https://github.com/freshworks/crayons/issues/696
> fix(tabs): handle activate-tab-name property correctly

- packages/crayons-core/src/components/tab/readme.md
- packages/crayons-core/src/components/tab/tab.scss
- packages/crayons-core/src/components/tabs/readme.md
- packages/crayons-core/src/components/tabs/tabs.scss
> chore(tab-border): added border styles for tabs as variable

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): timepicker popup in datetimepicker

- packages/crayons-core/src/components/tab/tab.scss
> fix(tab): update styles for focus-visible for tab

- packages/crayons-core/src/components/tabs/tabs.tsx
> fix(tabs): fix activateTab with tab-name

- packages/crayons-core/src/components/input/input.scss
- packages/crayons-core/src/components/select/select.scss
> chore(select-transition): applied transition for the border on hover and focus

- packages/crayons-core/src/components/datepicker/datepicker.tsx
Fixes: https://github.com/freshworks/crayons/issues/707
> fix(datepicker): handle minDate, maxDate when set dynamically

- packages/crayons-core/src/components/data-table/data-table.tsx
- packages/crayons-extended/custom-objects/src/components/platform-table/sort-select/sort-select.tsx
- packages/crayons-i18n/i18n/en-US.json
> feat: add i18n strings for sort-select and datatable

- packages/crayons-core/src/components/select/select.scss
> style: use border variable for select when disabled

- packages/crayons-core/src/components/form/readme.md
added example for using form inside an accordian
> docs(fw-form): update fw-form documentation

- packages/crayons-icon/package.json
> chore(package version): bump crayons-icon version to 4 to keep in sync with dist-tag v4

- packages/crayons-core/src/components/form/readme.md
> docs(form): update form documentation

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): avoid using non-standard event.path

- packages/crayons-core/src/components/form-control/form-control.e2e.ts
- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/form/form.e2e.ts
- packages/crayons-core/src/components/form/readme.md
- updated test cases for form and form control
> Handle FormServ field_options object in form control

- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/form/form-util.ts
- packages/crayons-core/src/components/form/form.e2e.ts
- packages/crayons-core/src/components/form/form.tsx
- packages/crayons-core/src/index.html
- packages/crayons-core/stencil.config.ts
> feat(form): custom mapper with watcher

- packages/crayons-core/src/components/data-table/data-table.e2e.ts
- packages/crayons-core/src/components/data-table/data-table.tsx
[Issue](https://github.com/freshworks/crayons/issues/747)
> fix: issue with unselecting columns in data table

- packages/crayons-core/src/components/button-group/button-group.tsx
Added mutuation observer to watch changes to the element
> fix(button-group): fix button group styling collapse

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/form/form-declaration.ts
- packages/crayons-core/src/components/form/form-util.ts
- packages/crayons-core/src/components/form/form.e2e.ts
- packages/crayons-core/src/components/form/form.tsx
- packages/crayons-core/src/components/form/readme.md
- packages/crayons-core/src/index.html
1. exposed setFieldSearchText method to filter form fields
2. added implicit validations on static forms via slots
> feat(form): searchable form fields and implicit validation on static forms

- styles/_utils.scss
- www/css-utils/layout/readme.md
> chore(css-utils): add gap utils

- packages/crayons-core/stencil.config.ts
- packages/crayons-extended/custom-objects/stencil.config.ts
> build(stencil): create es5 bundle only in production mode. speeds up dev server and HMR

- packages/crayons-core/src/components/select/select.tsx
> fix: revert readonly changes

- packages/crayons-core/src/components/select/select.scss
> style: style change for disabled multi select

- packages/crayons-core/src/components/accordion-body/accordion-body.tsx
- packages/crayons-core/src/components/accordion-title/accordion-title.tsx
- packages/crayons-core/src/components/button-group/button-group.tsx
- packages/crayons-core/src/components/form-control/form-control.tsx
- packages/crayons-core/src/components/menu-item/menu-item.tsx
- packages/crayons-core/src/components/modal-content/modal-content.tsx
- packages/crayons-core/src/components/modal-footer/modal-footer.tsx
- packages/crayons-core/src/components/modal-title/modal-title.tsx
- packages/crayons-core/src/components/radio-group/radio-group.tsx
- packages/crayons-core/src/components/select-option/select-option.tsx
- packages/crayons-core/src/components/tab-panel/tab-panel.tsx
- packages/crayons-core/src/components/tabs/tabs.tsx
- packages/crayons-core/src/components/toast-message/toast-message.tsx
- packages/crayons-core/src/components/toggle-group-button/toggle-group-button.tsx
- packages/crayons-core/src/components/toggle-group/toggle-group.tsx
- www/.vuepress/config.js
- www/scripts/reorganize.js
**Revamped Sidebar for reference:**
> docs(sidebar): update sidebar

- .github/workflows/delete-gh-pages.yml
- .github/workflows/preview-deploy.yml
- delete-pages.sh
- packages/crayons-core/src/components/button/button.tsx
- www/.vuepress/config.js
> chore(button): make temp changes to check preview deploy

- .github/workflows/delete-gh-pages.yml
- .github/workflows/preview-deploy.yml
- delete-pages.sh
- packages/crayons-core/src/components/button/button.tsx
- www/.vuepress/config.js
> Test preview deploy

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/form/form.e2e.ts
- packages/crayons-core/src/components/form/form.tsx
- packages/crayons-core/src/components/form/readme.md
> feat(form): expose api for setting field choices dynamically

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/spinner/readme.md
- packages/crayons-core/src/components/spinner/spinner.tsx
Introducing a micro variant of spinner in Crayons.
> feat(fw-spinner): adding a micro variant size for spinner component

- packages/crayons-core/src/components/datepicker/datepicker.e2e.ts
- packages/crayons-core/src/components/datepicker/datepicker.scss
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/timepicker/timepicker.tsx
[Github issue](https://github.com/freshworks/crayons/issues/777#issue-1535865173)
This PR contains timepicker issue and datepicker issue.
Doc for [reference](https://docs.google.com/document/d/1jYtWmQrFy3JhDzvj8ZaEzixvO5zLtHIg7mFNz5UmKnc/edit)
> fix(date-picker): fix min/max year restriction issue

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): replace event.path with event.composedPath() to fix breaking changes in chrome

- package-lock.json
- packages/crayons-core/package.json
- packages/crayons-core/src/components/file-uploader-2/file-uploader-2.e2e.ts
> test(file-uploader-2): adding api mock using pretender for file uploader 2

- packages/crayons-core/src/components/select/select.scss
- packages/crayons-core/src/components/select/select.tsx
> fix: disable caret when disabled in fw-select

- packages/crayons-core/src/components/form/readme.md
> docs(form): code samples to pass crayons input control related properties via fieldProps or via schema

- packages/crayons-core/src/components/options-list/list-options.e2e.ts
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/select/select.e2e.ts
- packages/crayons-core/src/components/select/select.tsx
> fix: fix re-render value on options change

- packages/crayons-extended/custom-objects/src/components/form-builder/assets/form-mapper.json
- packages/crayons-extended/custom-objects/src/components/form-builder/components/fb-field-dropdown.tsx
- packages/crayons-extended/custom-objects/src/components/form-builder/components/field-editor.tsx
- packages/crayons-extended/custom-objects/src/components/form-builder/form-builder.e2e.ts
- packages/crayons-extended/custom-objects/src/components/form-builder/utils/form-builder-utils.ts
> chore(fb-chat-fixes-0103): updated limits of all the field types and bug fixes

- packages/crayons-extended/custom-objects/src/components/form-builder/form-builder.e2e.ts
> test: modified tests to make use of form mapper

- packages/crayons-core/src/components/select/select.e2e.ts
- packages/crayons-core/src/components/select/select.tsx
> fix: fix deletion when readonly is set to true

- packages/crayons-core/src/components/form/form.tsx
> fix(form): reset the value of the form field when setFieldChoices is called

- packages/crayons-core/src/components/form/form-util.ts
- packages/crayons-core/src/components/form/readme.md
- www/.vuepress/config.js
- www/.vuepress/public/global/header.esm.js
> docs(form): added Yup based form validation with live examples.Injecting global scripts in docs site

- packages/crayons-core/src/components/modal/readme.md
> Enhance content of react JSX modal tag

- packages/crayons-extended/custom-objects/src/components/form-builder/form-builder.e2e.ts
> test: add tests for form builder new scenarios

- packages/crayons-core/src/components/datepicker/datepicker.tsx
This PR contains fix for date range picker validation scenarios.
https://monumental-hamster-acb120.netlify.app/components/core/datepicker/#demo
> fix(fw-daterangepicker): add input validations for date range picker

- packages/crayons-core/README.md
- packages/crayons-core/src/components/icon/readme.md
- packages/crayons-icon/README.md
- www/css-utils/installation/readme.md
- www/introduction/migrating-to-v3/readme.md
- www/introduction/migrating-to-v4/readme.md
- www/introduction/readme.md
- www/scripts/template.txt
> docs(crayons): replace unpkg.com imports with jsDelivr imports in the docs

- packages/crayons-extended/custom-objects/src/components/form-builder/components/field-editor.tsx
- packages/crayons-extended/custom-objects/src/components/form-builder/utils/form-builder-utils.ts
- packages/crayons-extended/custom-objects/src/index.html
> chore(fb-role-edit): allow checkbox edit for free user plan enabled

- packages/crayons-core/src/components/datepicker/datepicker.e2e.ts
- packages/crayons-core/src/components/datepicker/datepicker.tsx
This PR contains unit test cases for date range picker input validation scenarios and the fix for the date time picker [bug](https://github.com/freshworks/crayons/issues/835)
Link to test the fix: https://monumental-hamster-acb120.netlify.app/components/core/datepicker/#date-time-picker
> test(fw-datepicker): add unit test cases for date range picker

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/datepicker/readme.md
- packages/crayons-core/src/index.html
Link to test the changes: https://monumental-hamster-acb120.netlify.app/components/core/datepicker/#demo
> fix(datepicker): handle clear input scenario for invalid inputs

- packages/crayons-core/src/components.d.ts
- packages/crayons-core/src/components/datepicker/datepicker.scss
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/form/readme.md
> feat(datepicker): add a prop to make the datepicker occupy full width

- packages/crayons-core/src/components/input/input.e2e.ts
- packages/crayons-core/src/components/input/input.tsx
- packages/crayons-core/src/components/input/readme.md
> feat: add keydown event in input component

- packages/crayons-core/src/components/datepicker/datepicker.tsx
> fix(datepicker): handle user timezone offset

- packages/crayons-i18n/i18n/en-US.json
> chore(co-add-rec): added text for add record feature for translation

- packages/crayons-core/src/components/datepicker/datepicker.e2e.ts
- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/datepicker/readme.md
> fix(timepicker): fix timepicker issues

- packages/crayons-core/src/components/options-list/list-options.e2e.ts
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/select-option/select-option.e2e.ts
- packages/crayons-core/src/components/select-option/select-option.scss
- packages/crayons-core/src/components/select-option/select-option.tsx
> fix: styling of checkbox in Select Option, dynamically modify checkbox property in List Options

- packages/crayons-core/src/components/options-list/list-options.e2e.ts
- packages/crayons-core/src/components/options-list/list-options.tsx
- packages/crayons-core/src/components/select-option/select-option.e2e.ts
- packages/crayons-core/src/components/select-option/select-option.tsx
> fix(fw-list-options): remove checkbox for default options

- packages/crayons-core/src/components/select-option/select-option.e2e.ts
- packages/crayons-core/src/components/select-option/select-option.tsx
> Feat/default case for fw-select-option

- packages/crayons-core/src/components/datepicker/datepicker.tsx
- packages/crayons-core/src/components/form/form-util.ts
> fix(form): handle timezone for datepicker when serializing form values

- packages/crayons-core/src/components/select/select.scss
Reference: https://github.com/freshworks/crayons/issues/872#issuecomment-1611341028
> style(fw-select): fix container width calculation
